services:
  - type: web
    name: videotube-api
    runtime: node
    rootDir: backend
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/healthcheck
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: REFRESH_TOKEN_EXPIRY
        value: 10d
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
